### ISSUE TITLE
[BUG]: centroidal_smooth fails when applied to the triangulation of a sphere, Möbius strip, or Swiss roll.

### ISSUE THREAD

**Issue by sdall** [JuliaGeometry/DelaunayTriangulation.jl#177]
**Describe the bug**

`centroidal_smooth` fails when applied to the triangulation of a sphere, Möbius strip, or Swiss roll. 

**Edit:** It appears that `centroidal_smooth` fails on triangulations of 3D data. If this is to be expected, 
we might want to include an assertion or argument check to prevent the misusage of `centroidal_smooth`? 

```
ERROR: DimensionMismatch: array could not be broadcast to match destination
Stacktrace:
  [1] check_broadcast_shape
    @ ./broadcast.jl:579 [inlined]
  [2] check_broadcast_axes
    @ ./broadcast.jl:582 [inlined]
  [3] instantiate
    @ ./broadcast.jl:317 [inlined]
  [4] materialize!
    @ ./broadcast.jl:914 [inlined]
  [5] materialize!
    @ ./broadcast.jl:911 [inlined]
  [6] set_point!(points::Matrix{Float64}, i::Int64, x::Float64, y::Float64)
    @ DelaunayTriangulation ~/.julia/packages/DelaunayTriangulation/kmDdN/src/geometric_primitives/points.jl:534
  [7] move_generator_to_centroid!(points::Matrix{Float64}, vorn::VoronoiTessellation{Triangulation{…}, Tuple{…}, Int64, Tuple{…}, Set{…}, Tuple{…}}, generator::Int64)
    @ DelaunayTriangulation ~/.julia/packages/DelaunayTriangulation/kmDdN/src/algorithms/voronoi/centroidal.jl:19
  [8] _centroidal_smooth_itr(vorn::VoronoiTessellation{…}, set_of_boundary_nodes::Set{…}, points::Matrix{…}, rng::Random.TaskLocalRNG, predicates::FastKernel; kwargs::@Kwargs{})
    @ DelaunayTriangulation ~/.julia/packages/DelaunayTriangulation/kmDdN/src/algorithms/voronoi/centroidal.jl:66
  [9] _centroidal_smooth_itr(vorn::VoronoiTessellation{…}, set_of_boundary_nodes::Set{…}, points::Matrix{…}, rng::Random.TaskLocalRNG, predicates::FastKernel)
    @ DelaunayTriangulation ~/.julia/packages/DelaunayTriangulation/kmDdN/src/algorithms/voronoi/centroidal.jl:61
 [10] centroidal_smooth(vorn::VoronoiTessellation{…}; maxiters::Int64, tol::Float64, rng::Random.TaskLocalRNG, predicates::FastKernel, kwargs::@Kwargs{})
    @ DelaunayTriangulation ~/.julia/packages/DelaunayTriangulation/kmDdN/src/algorithms/voronoi/centroidal.jl:109
 [11] top-level scope
    @ REPL[107]:1
Some type information was truncated. Use `show(err)` to see complete types.
```

**Reproducer**

Give a minimal working example of your bug here, e.g. something like

```julia
function sphere(num_samples)
    x(z, t) = sqrt(1 - z^2) * cos(t)
    y(z, t) = sqrt(1 - z^2) * sin(t)
    
    z = -1 .+ 2.0 .* rand(num_samples)
    t = 2*pi .* rand(num_samples)

    [x.(z, t) y.(z, t) z]
end

points = sphere(500) |> permutedims

tri1 = triangulate(points) # default predicate kernel is AdaptiveKernel()

# Voronoi example 
vorn2 = voronoi(tri1)

# Clipped Voronoi 
vorn3 = voronoi(tri1, clip=true, predicates = ExactKernel())

# Smoothed Voronoi 
vorn4 = centroidal_smooth(vorn3, predicates = FastKernel())

```

Describe what you expected to obtain.

Post the result of doing

```julia
Julia Version 1.10.4
Commit 48d4fd48430 (2024-06-04 10:41 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: macOS (arm64-apple-darwin22.4.0)
  CPU: 8 × Apple M3
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, apple-m1)
Threads: 1 default, 0 interactive, 1 GC (on 4 virtual cores)
```

and

```julia
Status `/private/var/folders/4b/n411ykkn7rjfvqpp_m4q3h340000gn/T/jl_VqGLHv/Project.toml`
  [13f3f980] CairoMakie v0.12.9
  [927a84f5] DelaunayTriangulation v1.1.4
```

**Comment by DanielVandH** [comment]
Away from the computer right now but are you trying to triangulate points in 3D? This package currently only works for points in the plane. The triangulate works because it just ignored the z-coordinates

**Comment by DanielVandH** [comment]
Ah missed what you mention about assertions. That could be a good idea

**Comment by sdall** [comment]
Thanks for getting back to me so quickly! I must have missed that this package is all about 2D---sorry about that. After I reported the issue, I wondered if the third dimension could be the cause and made some edits to my report.
I like your idea to add safeguards to all algorithms: since the triangulation of 3D data didn’t throw any errors, I thought at first that I encountered a bug instead of a user error.

Please feel free to close the issue.

**Comment by DanielVandH** [comment]
> I must have missed that this package is all about 2D---sorry about that.

No worries. I'm not sure there is a Julia package that can handle this yet unfortunately (other than the wrapper TetGen.jl maybe?). 3D is on my to-do list but unfortunately the to-do list already has quite a backlog 😅 

I'll leave this issue open for now just as a reminder to myself to add those assertions at some point to make issues like yours more obvious. Thanks.

**Comment by sdall** [comment]
Thank you very much for your support and great work!
I think the first sentence of your README clearly states that it is about planar triangulations, but I was a bit distracted by your great example, which invited me to directly jump into a REPL.  :-)

All the best.

**Comment by DanielVandH** [comment]
I think I might just not do anything since there are actually some cases where it is useful to triangulate points in 3D ignoring the $z$-coordinate (e.g. for interpolating data $z = f(x, y)$) so erroring in `triangulate` would be breaking. I could add an `is_planar(points)` trait into `centroidal_smooth` and check there (if `check_args=true`) but it might be a bit confusing if that errors and nothing else errors. The error you saw is because

```julia
set_point!(points::AbstractMatrix, i, x, y) = points[:, i] .= (x, y)
```

is a bad definition. For now I'll just change it to

```julia
set_point!(points::AbstractMatrix, i, x, y) = (points[1, i] = x; points[2, i] = y)
```

with https://github.com/JuliaGeometry/DelaunayTriangulation.jl/pull/178. Maybe it's not ideal since it'll just silently not give a 3D triangulation but it at least allows for ignoring the $z$-coordinate like the other algorithms.

**Comment by sdall** [comment]
Sounds like a good compromise!
To avoid a breaking change, could we print a warning instead of throwing an error as potential future work?

**Comment by DanielVandH** [comment]
Oh yeah that could be good. Something like

```julia
function check_dimension(points)
    cert = is_planar(points) # default: all(is_point2, each_point(points))
    if !cert 
        @warn "This package currently only supports points in the plane. By default, all the z-coordinates will be ignored." maxlog=1
    end
end
```

**Comment by DanielVandH** [comment]
https://github.com/JuliaGeometry/DelaunayTriangulation.jl/pull/178 now implements your idea. Once this is in your example would show a warning at the first `triangulate`.

**Comment by DanielVandH** [comment]
Thanks for the issue!
