### ISSUE TITLE
[JOSS] Review comments

### ISSUE THREAD

**Issue by mtsch** [JuliaGeometry/DelaunayTriangulation.jl#189]
Hi,

First of all, sorry for taking such a long time to review your JOSS submission! I must say this is the perfect example of a high-quality package. I'm especially impressed by the docs as I've found them easy to read and I feel like they cover everything.

I think overall the paper is very good, but I have two minor comments:

- Since the docs contains such a nice mathematical details section, I'd suggest you link to them in the paper at the end of the summary section. This way, an interested reader will be immediately know where look to learn more details about the methods.
- In the example, I suggest adding a few more words about mean exit times, in particular where they come up or even a short definition of them. I'm not familiar with the field, so I got a bit confused there until you started discussing the equations in more detail later.

Cheers!

**Comment by DanielVandH** [comment]
Hi @mtsch, thanks for your review and kind words! No worries at all for the delay.

> Since the docs contains such a nice mathematical details section, I'd suggest you link to them in the paper at the end of the summary section. This way, an interested reader will be immediately know where look to learn more details about the methods.

This is a good suggestion. I have now added "A more detailed description of these mathematical details can
be found in the package’s [documentation](https://juliageometry.github.io/DelaunayTriangulation.jl/stable/math/overview/)." at the end of the summary.

> In the example, I suggest adding a few more words about mean exit times, in particular where they come up or even a short definition of them. I'm not familiar with the field, so I got a bit confused there until you started discussing the equations in more detail later.

Thanks for pointing this out. You're right that it's a bit confusing currently. To address this, I have mentioned its applications when introducing the concept, and I introduce the notation $T(x, y)$ before the list of equations describing the mathematical model. Hopefully that makes it clearer!

I have regenerated the PDF over at https://github.com/openjournals/joss-reviews/issues/7174 so you can see these changes.

**Comment by mtsch** [comment]
Looks great! I think there's a typo in line 66. It reads:

> one model describing the mean exit time of a particle existing Ω

I believe you meant

> one model describing the mean exit time of a particle exiting Ω

Might even read better as

> one model describing the mean time of a particle exiting Ω

but that's up to you.

After this change I'll be happy to approve your submission.

**Comment by DanielVandH** [comment]
Thanks for spotting that! I have now fixed the typo.

**Comment by mtsch** [comment]
Perfect!
