### ISSUE TITLE
[JOSS]: Editing comments

### ISSUE THREAD

**Issue by vissarion** [JuliaGeometry/DelaunayTriangulation.jl#190]
I have some comments that may improve the writing of the JOSS paper. 

- In the definition of the Delaunay triangulation (second paragraph "Given a set of points...") it seems that this is the definition of constraint Delaunay triangulation, which is in general not a problem since Delaunay is a special case but I think it should somehow me mentioned in the text to avoid confusion. Additionally, the definition does not mention the Delaunay property so it actually defines any triangulation (not necessarily the Delaunay one).

- In "Statement of need" in the second paragraph "Several software packages with support..." it would be useful to also state the programming language the software package is written (e.g. C++ for CGAL, C for Triangle etc). Also how your package compares to those packages? Especially to [gmsh](https://gmsh.info/) that has a Julia interface. 

- There are some minor typos: 
  - in ref "Aurenhammer, F., Klein..." delaunay should be capitalized
  - "... although none are as developed as ...", I think it is better "... although none is as developed as..."

**Comment by DanielVandH** [comment]
Thanks @vissarion! 

> In the definition of the Delaunay triangulation (second paragraph "Given a set of points...") it seems that this is the definition of constraint Delaunay triangulation, which is in general not a problem since Delaunay is a special case but I think it should somehow me mentioned in the text to avoid confusion. Additionally, the definition does not mention the Delaunay property so it actually defines any triangulation (not necessarily the Delaunay one).

Thanks for pointing this out, that's an oversight on my part. I'll correct this and, to help separate the cases, will first define Delaunay triangulations and then their constrained generalisation. I'll also mention the Delaunay property.

> In "Statement of need" in the second paragraph "Several software packages with support..." it would be useful to also state the programming language the software package is written (e.g. C++ for CGAL, C for Triangle etc). Also how your package compares to those packages? Especially to [gmsh](https://gmsh.info/) that has a Julia interface.

I'll add the programming languages used, thanks for mentioning that. Regarding the comparison, I didn't include them because of space reasons. What do you think about instead including a comparison to those non-Julia packages to the README instead, since I already link to that for Julia alternatives? I'm happy to try and include it in the paper directly if you think that is a better alternative, though.

> There are some minor typos:

Thanks!

**Comment by vissarion** [comment]
> I'll add the programming languages used, thanks for mentioning that. Regarding the comparison, I didn't include them because of space reasons. What do you think about instead including a comparison to those non-Julia packages to the README instead, since I already link to that for Julia alternatives? I'm happy to try and include it in the paper directly if you think that is a better alternative, though.

Adding them in the README together with other comparisons seems the best option.

**Comment by DanielVandH** [comment]
Thanks again for your comments @vissarion. I've added that now to the README and also now include this table which is hopefully detailed enough! I've regenerated the PDF now over at the review for you to check.

![softwarecomparison](https://github.com/user-attachments/assets/4bedbf30-5be0-44e1-8710-3f0c63e69305)
