### ISSUE TITLE
[BUG]: clipping when getting polygon from Voronoi tessellation hangs for certain configurations

### ISSUE THREAD

**Issue by rubenseyer** [JuliaGeometry/DelaunayTriangulation.jl#206]
**Describe the bug**

I want to perform a Voronoi tessellation of a periodic window, but I'm solving this by making mirror copies of points where necessary and then clipping my polygons to the original bounding box. Thus, in an edge case, the resulting set of points can lie on a triangle (up to floating point precision). Some of these configurations seem to hang for me when attempting to get the clipped polygons.

**Reproducer**

```julia
using DelaunayTriangulation
using Random: seed!

seed!(123) # randomness is not relevant here, but just to be sure
pts = [(0.1,0.2), (1.1,0.2), (0.1,1.2)]
D = triangulate(pts)
V = voronoi(D)
bbox = (0., 1., 0., 1.)
get_polygon_coordinates(V, 3, bbox)  # hangs
```
I expect to obtain the clipped polygons rather than the code hanging.

**Environment information**

```
Julia Version 1.10.2
Commit bd47eca2c8a (2024-03-01 10:14 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 12 × 12th Gen Intel(R) Core(TM) i5-1245U
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, alderlake)
Threads: 1 default, 0 interactive, 1 GC (on 12 virtual cores)
Environment:
  JULIA_EDITOR = code
  JULIA_NUM_THREADS = 
```

```
Status `~/xyz/Project.toml`
  [927a84f5] DelaunayTriangulation v1.6.0
```

**Comment by DanielVandH** [comment]
Can you try https://github.com/JuliaGeometry/DelaunayTriangulation.jl/pull/207 and see if it fixes your use case?

**Comment by rubenseyer** [comment]
Thanks for the quick response (and sorry I didn't run that in time for you earlier)!
You correctly inferred that I meant a (possibly up to numerics) *right* triangle :sweat_smile:
I stress-tested your fix with the outer generating code and it doesn't hang any more for me, so I consider this fixed for my purposes. Now I just have to convince Makie to bump their compat bounds from `1.0` so I can actually install the new version in the rest of the environment.

**Comment by DanielVandH** [comment]
Great! I will make a new release with the fix.

> Now I just have to convince Makie to bump their compat bounds from 1.0 so I can actually install the new version in the rest of the environment.

It should be all up to date on Makie's side as well. You probably have an outdated environment (use `]st --outdated` to see what might be holding it back).
