### ISSUE TITLE
name too long (ENAMETOOLONG) in a test file

### ISSUE THREAD

**Issue by matbesancon** [JuliaGeometry/DelaunayTriangulation.jl#211]
When installing a package depending on this one:

ERROR: Error when installing package DelaunayTriangulation:
IOError: open("/home/matbesancon/.julia/packages/DelaunayTriangulation/74rOt/test/refinement/refine_curve_bounded_example_11_multiply_connected_piecewise_linear_elliptical_bspline_piecewise_linear_catmull_bezier_piecewise_linear_circle_default_5310379833384766060.png", 577, 33188): name too long (ENAMETOOLONG)

**Comment by DanielVandH** [comment]
I had no idea there could be filename restrictions. I'll trim the filenames later today.

**Comment by matbesancon** [comment]
me neither, this is a first!

**Comment by DanielVandH** [comment]
@matbesancon Hopefully https://github.com/JuliaGeometry/DelaunayTriangulation.jl/pull/212 fixes it. Do you want to see if all the file names are now an appropriate length before I merge it?
